# Kernel compile workflow for personal usage
# By Sarthak Roy (sarthakroy2002@gmail.com)

name: Kernel CI

on:
  workflow_dispatch:
    inputs:
      repo:
          description: 'Kernel source link'
          required: true
      branch:
          description: 'Kernel source branch'
          required: true   

env:
  TZ: Asia/Kolkata
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  token: https://api.telegram.org/bot2030871213
  chat_id: "chat_id-1001567409765"

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:



      - name: Initializing environment
        run: |
          git config --global user.name "Synchroz"
          git config --global user.email "juliyanto1071@student.untan.ac.id"
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch



      - name: Lets compile
        run: |
          git clone --depth=1 https://github.com/Synchroz/newtoni kernel 
          cd kernel 
          wget  https://github.com/Synchroz/newtoni/build.sh
          bash build.sh
